name: wellness_hub_australia
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ez_core:
    path: ./packages/ez_core
  ez_ui:
    path: ./packages/ez_ui
  ez_dashboard:
    path: ./packages/ez_dashboard
  ez_onboarding:
    path: ./packages/ez_onboarding
  #intro_slider: ^4.2.0
  #date_picker_timeline: ^1.2.3
# Primary
  #awesome_notifications: ^0.7.3
  #fluttertoast: ^8.0.8
  flutter_native_splash: ^2.2.13
  google_fonts: ^3.0.1
  dash_chat_2: ^0.0.15
# State Management
  logger: ^1.1.0
  provider: ^6.0.3
  stacked: ^3.0.0
  stacked_services: ^0.9.4
  stacked_generator: ^0.8.0+1
  stacked_themes: ^0.3.9
  auto_route: ^5.0.2
  auto_route_generator: ^5.0.3
  #connectivity_plus: ^2.3.6+1
  #universal_io: ^2.0.4
  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0
# Widgets
  percent_indicator: ^4.0.0
  #data_table_2: ^2.2.1
  #badges: ^2.0.2
  #transparent_image: ^2.0.0
  eva_icons_flutter: ^3.0.2
  #introduction_screen: ^3.0.0
  flutter_staggered_grid_view: ^0.6.2
  #flutter_staggered_animations: "^1.0.0"
  #widget_and_text_animator: ^1.0.9
  flutter_widget_from_html: ^0.8.5
  cached_network_image: ^3.2.0
  modal_bottom_sheet: ^2.0.1
  #auto_size_text: ^3.0.0
  timeago: ^3.2.2
  #styled_widget: ^0.4.0+3
  syncfusion_flutter_calendar: ^20.1.57
  syncfusion_flutter_charts: ^20.1.57
  #syncfusion_flutter_datagrid: ^20.1.57
  #geolocator: ^9.0.1
  #geocoding: ^2.0.4
  #quiver: ^3.1.0
  #flutter_awesome_select: ^6.4.0
# Form Widget
  flutter_form_builder: ^7.7.0
  form_builder_extra_fields: ^8.3.0
  form_builder_validators: ^8.3.0
  form_builder_image_picker: ^3.1.0
  mask_text_input_formatter: ^2.4.0
# UI Utilities
  hexcolor: ^2.0.5
  #theme_provider: ^0.5.0
  responsive_builder: ^0.4.2
# Helpers
  http: ^0.13.4
  http_interceptor: ^2.0.0-beta.5
  http_parser: ^4.0.1
  dio: ^4.0.6
  shared_preferences: ^2.0.13
  equatable: ^2.0.3
  intl: ^0.17.0
  faker: ^2.0.0
  url_launcher: ^6.1.2
  #uuid: ^3.0.6
  #retrofit: ^3.0.1+1
  #animations: ^2.0.3
  scrollable_positioned_list: ^0.3.2
  dotted_border: ^2.0.0+2
  flutter_map: ^2.2.0
  latlong2: ^0.8.1
  smooth_page_indicator: ^1.0.0+2
  #another_transformer_page_view: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.2
  analyzer: ^5.1.0
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.0.1
  json_serializable: ^6.1.4
  freezed: ^2.0.3
  
  dependency_validator: ^3.1.2
  flutter_launcher_icons: ^0.10.0

dependency_overrides:
  image_picker_android: 0.8.4+13
  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/images/
    - assets/images/onboard/
    - assets/ca/
    - assets/json/au_postcodes.json
    - google_fonts/poppins/

  uses-material-design: true

